pub const Key = enum {
    Left,
    Right,
    Down,
    Up,
    Shift,
    Control,
    Alt,
    Super,
    CapsLock,
    Escape,
    Tab,
    Space,
    Enter,
    Backspace,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
};

// source: https://eastmanreference.com/complete-list-of-applescript-key-codes
pub fn macos_keycode(key: Key) u16 {
    return switch (key) {
        .Left => 123,
        .Right => 124,
        .Down => 125,
        .Up => 126,

        .Shift => 56,
        .Control => 59,
        .Alt => 58,
        .Super => 55,
        .CapsLock => 57,

        .Escape => 53,
        .Tab => 48,
        .Space => 49,
        .Enter => 36,
        .Backspace => 51,
        .Delete => 117,
        .Home => 115,
        .End => 119,
        .PageUp => 116,
        .PageDown => 121,

        .Num0 => 29,
        .Num1 => 18,
        .Num2 => 19,
        .Num3 => 20,
        .Num4 => 21,
        .Num5 => 23,
        .Num6 => 22,
        .Num7 => 26,
        .Num8 => 28,
        .Num9 => 25,

        .A => 0,
        .B => 11,
        .C => 8,
        .D => 2,
        .E => 14,
        .F => 3,
        .G => 5,
        .H => 4,
        .I => 34,
        .J => 38,
        .K => 40,
        .L => 37,
        .M => 46,
        .N => 45,
        .O => 31,
        .P => 35,
        .Q => 12,
        .R => 15,
        .S => 1,
        .T => 17,
        .U => 32,
        .V => 9,
        .W => 13,
        .X => 7,
        .Y => 16,
        .Z => 6,
    };
}

// source: https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h
pub fn linux_keycode(key: Key) u16 {
    return switch (key) {
        .Left => 105 + 8,
        .Right => 106 + 8,
        .Down => 108 + 8,
        .Up => 103 + 8,

        .Shift => 42 + 8,
        .Control => 29 + 8,
        .Alt => 56 + 8,
        .Super => 125 + 8,
        .CapsLock => 58 + 8,

        .Escape => 1 + 8,
        .Tab => 15 + 8,
        .Space => 57 + 8,
        .Enter => 28 + 8,
        .Backspace => 14 + 8,
        .Delete => 111 + 8,
        .Home => 102 + 8,
        .End => 107 + 8,
        .PageUp => 104 + 8,
        .PageDown => 109 + 8,

        .Num0 => 11 + 8,
        .Num1 => 2 + 8,
        .Num2 => 3 + 8,
        .Num3 => 4 + 8,
        .Num4 => 5 + 8,
        .Num5 => 6 + 8,
        .Num6 => 7 + 8,
        .Num7 => 8 + 8,
        .Num8 => 9 + 8,
        .Num9 => 10 + 8,

        .A => 30 + 8,
        .B => 48 + 8,
        .C => 46 + 8,
        .D => 32 + 8,
        .E => 18 + 8,
        .F => 33 + 8,
        .G => 34 + 8,
        .H => 35 + 8,
        .I => 23 + 8,
        .J => 36 + 8,
        .K => 37 + 8,
        .L => 38 + 8,
        .M => 50 + 8,
        .N => 49 + 8,
        .O => 24 + 8,
        .P => 25 + 8,
        .Q => 16 + 8,
        .R => 19 + 8,
        .S => 31 + 8,
        .T => 20 + 8,
        .U => 22 + 8,
        .V => 47 + 8,
        .W => 17 + 8,
        .X => 45 + 8,
        .Y => 21 + 8,
        .Z => 44 + 8,
    };
}
