pub const Key = enum {
    Left,
    Right,
    Down,
    Up,
    Shift,
    Control,
    Alt,
    Super,
    CapsLock,
    Escape,
    Tab,
    Space,
    Enter,
    Backspace,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
};

// source: https://eastmanreference.com/complete-list-of-applescript-key-codes
pub fn macos_keycode(key: Key) u16 {
    return switch (key) {
        .Left => 123,
        .Right => 124,
        .Down => 125,
        .Up => 126,

        .Shift => 56,
        .Control => 59,
        .Alt => 58,
        .Super => 55,
        .CapsLock => 57,

        .Escape => 53,
        .Tab => 48,
        .Space => 49,
        .Enter => 36,
        .Backspace => 51,
        .Delete => 117,
        .Home => 115,
        .End => 119,
        .PageUp => 116,
        .PageDown => 121,

        .Num0 => 29,
        .Num1 => 18,
        .Num2 => 19,
        .Num3 => 20,
        .Num4 => 21,
        .Num5 => 23,
        .Num6 => 22,
        .Num7 => 26,
        .Num8 => 28,
        .Num9 => 25,

        .A => 0,
        .B => 11,
        .C => 8,
        .D => 2,
        .E => 14,
        .F => 3,
        .G => 5,
        .H => 4,
        .I => 34,
        .J => 38,
        .K => 40,
        .L => 37,
        .M => 46,
        .N => 45,
        .O => 31,
        .P => 35,
        .Q => 12,
        .R => 15,
        .S => 1,
        .T => 17,
        .U => 32,
        .V => 9,
        .W => 13,
        .X => 7,
        .Y => 16,
        .Z => 6,
    };
}
